# Generated by Django 4.2.9 on 2024-02-02 14:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=45)),
                ('manufacturer_name', models.CharField(max_length=200)),
                ('manufacturer_country', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=45)),
                ('pharmacy_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('available', models.CharField(max_length=3)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theracityApp.medicine')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theracityApp.pharmacy')),
            ],
        ),
    ]
